version: '3'
services:
  api:
    container_name: api_container
    image: api:latest
    build:
      context: .
      args:
        - PORT=$PORT
    environment: 
      - DBUSER=root
      - DBPASS=$DBPASS
      - DBNAME=$DBNAME
      - DBADDRESS=Database
      - DBPORT=3306
      - PORT=$PORT
    ports: 
      - $PORT:$PORT
    restart: on-failure
    depends_on:
      - Database        
    networks:
      - article_net


  Database:
    image: mysql:latest
    container_name: mysql_container
    environment: 
      - MYSQL_ROOT_PASSWORD=${DBPASS}
      - MYSQL_DATABASE=$DBNAME
    networks:
      - article_net
    volumes:
      - Database:/var/lib/mysql

volumes:
  Database:
    driver: local

networks:
  article_net:
    driver: bridge